
services:
  server:
    build: &server-build
      context: .
      target: local
    container_name: xend-server
    working_dir: /app
    depends_on:
      - postgres
      - redis
    ports:
       - "8008:8000"
    volumes:
      - ./:/app
    command: >
      bash -lc "
      poetry install --no-root &&
      poetry run python manage.py migrate &&
      poetry run uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include '*.html'"

  redis:
    image: redis:7
    container_name: xend-redis
    ports:
      - "6379:6379"
      
  postgres:
    image: postgres:15.3
    container_name: xend-postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data

  celery_worker:
    build: *server-build
    command: >
      bash -c "poetry run celery -A config.celery worker --loglevel=info --concurrency=2"
    volumes:
      - ./:/app
    depends_on:
      - server
    shm_size: "256m"

  celery_beat:
    build: *server-build
    command: >
      bash -c "poetry run celery -A config.celery beat --loglevel=info"
    depends_on:
      - server

  celery_flower:
    build: *server-build
    command: >
      bash -c "poetry run celery -A config.celery flower --port=5555 --basic-auth=fiveis:fiveis"
    ports:
      - "5555:5555"
    depends_on:
      - server
      - redis
      - celery_worker

  nginx:
    image: nginx:1.27-alpine
    container_name: xend-nginx
    depends_on: [server]
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - static_volume:/static:ro
      - media_volume:/media:ro
    ports:
      - "80:80"

volumes:
  pgdata:
#  static_volume:
  media_volume:
