version: "3.9"

services:
  server:
    build:
      context: .
      target: dev
    container_name: xend-server
    working_dir: /app
    depends_on:
       - redis
    ports:
       - "8008:8000"
    volumes:
      - ./:/app
    command: >
      bash -lc "
      poetry install --no-root &&
      poetry run python manage.py migrate &&
      poetry run uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include '*.html'"

  redis:
    image: redis:7
    container_name: xend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --loglevel debug
 
  nginx:
    image: nginx:1.27-alpine
    container_name: xend-nginx
    depends_on: [server]
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
#      - static_volume:/static:ro
      - media_volume:/media:ro
      - ./webroot:/var/www/certbot
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot:v2.11.0
    container_name: xend-certbot
    depends_on:
      - nginx
    volumes:
      - ./webroot:/var/www/certbot
      - ./certs:/etc/letsencrypt
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --deploy-hook 'nginx -s reload'; done"


volumes:
  pgdata:
#  static_volume:
  media_volume:
