version: "3.9"

services:
  server:
    build:
      context: .
      target: dev
    container_name: xend-server
    working_dir: /app
    ports:
       - "8008:8000"
    volumes:
      - ./:/app
    command: >
      bash -lc "
      poetry install --no-root &&
      poetry run python manage.py migrate &&
      poetry run uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include '*.html'"


  nginx:
    image: nginx:1.27-alpine
    container_name: xend-nginx
    depends_on: [server]
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - static_volume:/static:ro
      - media_volume:/media:ro
    ports:
      - "80:80"

volumes:
  pgdata:
#  static_volume:
  media_volume:
